"""addin email verified

Revision ID: 01c2ee94ff5f
Revises: d63178d97fb6
Create Date: 2026-01-14 16:56:53.936007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01c2ee94ff5f'
down_revision: Union[str, None] = 'd63178d97fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users_email_verification_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_users_email_verification_tokens_client_id'), 'app_users_email_verification_tokens', ['client_id'], unique=False)
    op.create_index(op.f('ix_app_users_email_verification_tokens_token'), 'app_users_email_verification_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_app_users_email_verification_tokens_user_id'), 'app_users_email_verification_tokens', ['user_id'], unique=False)
    op.add_column('app_users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('app_users', sa.Column('email_verified_at', sa.DateTime(), nullable=True))
    op.alter_column('two_factor_codes', 'is_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    op.create_index(op.f('ix_two_factor_codes_project_id'), 'two_factor_codes', ['project_id'], unique=False)
    op.create_index(op.f('ix_two_factor_codes_user_id'), 'two_factor_codes', ['user_id'], unique=False)
    op.alter_column('two_factor_settings', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    op.create_index(op.f('ix_two_factor_settings_project_id'), 'two_factor_settings', ['project_id'], unique=False)
    op.create_index(op.f('ix_two_factor_settings_user_id'), 'two_factor_settings', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_two_factor_settings_user_id'), table_name='two_factor_settings')
    op.drop_index(op.f('ix_two_factor_settings_project_id'), table_name='two_factor_settings')
    op.create_index('ix_2fa_settings_user_id', 'two_factor_settings', ['user_id'], unique=True)
    op.create_index('ix_2fa_settings_project_id', 'two_factor_settings', ['project_id'], unique=False)
    op.alter_column('two_factor_settings', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_two_factor_codes_user_id'), table_name='two_factor_codes')
    op.drop_index(op.f('ix_two_factor_codes_project_id'), table_name='two_factor_codes')
    op.create_index('ix_2fa_codes_user_id', 'two_factor_codes', ['user_id'], unique=False)
    op.create_index('ix_2fa_codes_project_id', 'two_factor_codes', ['project_id'], unique=False)
    op.alter_column('two_factor_codes', 'is_used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('cloud_functions', sa.Column('function_type', sa.VARCHAR(length=20), server_default=sa.text("'http'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('app_users', 'email_verified_at')
    op.drop_column('app_users', 'email_verified')
    op.drop_index(op.f('ix_app_users_email_verification_tokens_user_id'), table_name='app_users_email_verification_tokens')
    op.drop_index(op.f('ix_app_users_email_verification_tokens_token'), table_name='app_users_email_verification_tokens')
    op.drop_index(op.f('ix_app_users_email_verification_tokens_client_id'), table_name='app_users_email_verification_tokens')
    op.drop_table('app_users_email_verification_tokens')
    # ### end Alembic commands ###
