"""adding phone number field

Revision ID: 054e0b29e74f
Revises: e45bd15f6624
Create Date: 2026-01-19 19:06:44.831327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '054e0b29e74f'
down_revision: Union[str, None] = 'e45bd15f6624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('app_users', sa.Column('phone_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('app_users', sa.Column('phone_verified_at', sa.DateTime(), nullable=True))
    op.alter_column('two_factor_codes', 'code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_index('ix_2fa_codes_project_id', table_name='two_factor_codes')
    op.drop_index('ix_2fa_codes_user_id', table_name='two_factor_codes')
    op.drop_index('ix_2fa_settings_project_id', table_name='two_factor_settings')
    op.drop_index('ix_2fa_settings_user_id', table_name='two_factor_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_2fa_settings_user_id', 'two_factor_settings', ['user_id'], unique=True)
    op.create_index('ix_2fa_settings_project_id', 'two_factor_settings', ['project_id'], unique=False)
    op.create_index('ix_2fa_codes_user_id', 'two_factor_codes', ['user_id'], unique=False)
    op.create_index('ix_2fa_codes_project_id', 'two_factor_codes', ['project_id'], unique=False)
    op.alter_column('two_factor_codes', 'code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    op.add_column('cloud_functions', sa.Column('function_type', sa.VARCHAR(length=20), server_default=sa.text("'http'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('app_users', 'phone_verified_at')
    op.drop_column('app_users', 'phone_verified')
    op.drop_column('app_users', 'phone_number')
    # ### end Alembic commands ###
