"""adding email smtp models

Revision ID: 262dadc25e90
Revises: e61e0da1d83f
Create Date: 2026-01-07 18:26:08.290345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '262dadc25e90'
down_revision: Union[str, None] = 'e61e0da1d83f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_email_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_type', sa.Enum('WELCOME', 'VERIFICATION', 'FORGOT_PASSWORD', 'RESET_PASSWORD', 'PASSWORD_CHANGED', 'ACCOUNT_DELETED', 'LOGIN_ALERT', 'CUSTOM', name='emailtemplatetypeenum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('html_body', sa.Text(), nullable=False),
    sa.Column('text_body', sa.Text(), nullable=False),
    sa.Column('available_variables', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_default_email_templates_template_type'), 'default_email_templates', ['template_type'], unique=True)
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.Enum('WELCOME', 'VERIFICATION', 'FORGOT_PASSWORD', 'RESET_PASSWORD', 'PASSWORD_CHANGED', 'ACCOUNT_DELETED', 'LOGIN_ALERT', 'CUSTOM', name='emailtemplatetypeenum'), nullable=False),
    sa.Column('used_default_template', sa.Boolean(), nullable=True),
    sa.Column('template_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'BOUNCED', name='emailstatusenum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_log_project_created', 'email_logs', ['project_id', 'created_at'], unique=False)
    op.create_index('idx_email_log_status_created', 'email_logs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_email_logs_project_id'), 'email_logs', ['project_id'], unique=False)
    op.create_table('project_email_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.Enum('WELCOME', 'VERIFICATION', 'FORGOT_PASSWORD', 'RESET_PASSWORD', 'PASSWORD_CHANGED', 'ACCOUNT_DELETED', 'LOGIN_ALERT', 'CUSTOM', name='emailtemplatetypeenum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('html_body', sa.Text(), nullable=False),
    sa.Column('text_body', sa.Text(), nullable=False),
    sa.Column('available_variables', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default_override', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'template_type', name='uq_project_template_type')
    )
    op.create_index('idx_project_template_active', 'project_email_templates', ['project_id', 'template_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_project_email_templates_project_id'), 'project_email_templates', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_email_templates_template_type'), 'project_email_templates', ['template_type'], unique=False)
    op.create_table('smtp_configurations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('use_tls', sa.Boolean(), nullable=True),
    sa.Column('use_ssl', sa.Boolean(), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('hourly_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smtp_configurations_project_id'), 'smtp_configurations', ['project_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_smtp_configurations_project_id'), table_name='smtp_configurations')
    op.drop_table('smtp_configurations')
    op.drop_index(op.f('ix_project_email_templates_template_type'), table_name='project_email_templates')
    op.drop_index(op.f('ix_project_email_templates_project_id'), table_name='project_email_templates')
    op.drop_index('idx_project_template_active', table_name='project_email_templates')
    op.drop_table('project_email_templates')
    op.drop_index(op.f('ix_email_logs_project_id'), table_name='email_logs')
    op.drop_index('idx_email_log_status_created', table_name='email_logs')
    op.drop_index('idx_email_log_project_created', table_name='email_logs')
    op.drop_table('email_logs')
    op.drop_index(op.f('ix_default_email_templates_template_type'), table_name='default_email_templates')
    op.drop_table('default_email_templates')
    # ### end Alembic commands ###
