"""Add AI assistant conversation history and rate limiting tables

Revision ID: 29cdd01d72aa
Revises: a9ef5fd16185
Create Date: 2025-11-13 18:06:09.309040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29cdd01d72aa'
down_revision: Union[str, None] = 'a9ef5fd16185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
