"""indexin

Revision ID: 3d6b5b575219
Revises: 8331c0807af3
Create Date: 2025-11-04 10:02:19.244537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d6b5b575219'
down_revision: Union[str, None] = '8331c0807af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_users', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('ix_app_users_created_at', 'app_users', ['created_at'], unique=False)
    op.create_index('ix_app_users_data_gin', 'app_users', ['data'], unique=False, postgresql_using='gin', postgresql_ops={'data': 'jsonb_path_ops'})
    op.create_index('ix_documents_collection_created', 'documents', ['collection_id', 'created_at'], unique=False)
    op.create_index('ix_documents_created_at', 'documents', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_created_at', table_name='documents')
    op.drop_index('ix_documents_collection_created', table_name='documents')
    op.drop_index('ix_app_users_data_gin', table_name='app_users', postgresql_using='gin', postgresql_ops={'data': 'jsonb_path_ops'})
    op.drop_index('ix_app_users_created_at', table_name='app_users')
    op.alter_column('app_users', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
