"""added fields for rbac

Revision ID: 4d6bc24889d6
Revises: c9ea0c5d834f
Create Date: 2025-08-27 17:43:07.725968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d6bc24889d6'
down_revision: Union[str, None] = 'c9ea0c5d834f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('roles', sa.PickleType(), nullable=True))
    op.add_column('collections', sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'permissions')
    op.drop_column('app_users', 'roles')
    # ### end Alembic commands ###
