"""added limit pricing for cloud function

Revision ID: 5f20aff3fa35
Revises: f3254218ba4f
Create Date: 2025-10-11 23:42:56.207254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f20aff3fa35'
down_revision: Union[str, None] = 'f3254218ba4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_plans', sa.Column('max_cloud_functions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing_plans', 'max_cloud_functions')
    # ### end Alembic commands ###
