"""added webhook url

Revision ID: 6f35f72e4be1
Revises: bd2252169ec4
Create Date: 2025-06-08 19:38:57.220683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f35f72e4be1'
down_revision: Union[str, None] = 'bd2252169ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('webhook_url', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('callback_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'callback_url')
    op.drop_column('collections', 'webhook_url')
    # ### end Alembic commands ###
