"""changed field name

Revision ID: 7681473497d9
Revises: 641568de27d5
Create Date: 2025-06-09 21:18:38.125070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7681473497d9'
down_revision: Union[str, None] = '641568de27d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('app_users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('app_users', 'password')
    # ### end Alembic commands ###
