"""t

Revision ID: 7d178b12f129
Revises: 
Create Date: 2025-11-09 00:12:51.963719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d178b12f129'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_app_users_client_id'), 'app_users', ['client_id'], unique=False)
    op.create_unique_constraint('uq_client_email', 'app_users', ['client_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_client_email', 'app_users', type_='unique')
    op.drop_index(op.f('ix_app_users_client_id'), table_name='app_users')
    # ### end Alembic commands ###
