"""adding orm api key

Revision ID: 7fb6b7e93925
Revises: 262dadc25e90
Create Date: 2026-01-10 00:18:49.253458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fb6b7e93925'
down_revision: Union[str, None] = '262dadc25e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orm_api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orm_keys_active', 'orm_api_keys', ['is_active', 'project_id'], unique=False)
    op.create_index('idx_orm_keys_prefix', 'orm_api_keys', ['key_prefix'], unique=False)
    op.create_index('idx_orm_keys_project', 'orm_api_keys', ['project_id'], unique=False)
    op.create_index(op.f('ix_orm_api_keys_project_id'), 'orm_api_keys', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orm_api_keys_project_id'), table_name='orm_api_keys')
    op.drop_index('idx_orm_keys_project', table_name='orm_api_keys')
    op.drop_index('idx_orm_keys_prefix', table_name='orm_api_keys')
    op.drop_index('idx_orm_keys_active', table_name='orm_api_keys')
    op.drop_table('orm_api_keys')
    # ### end Alembic commands ###
