"""fixing stuff

Revision ID: 8331c0807af3
Revises: 094211e8220b
Create Date: 2025-11-03 17:04:48.729167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8331c0807af3'
down_revision: Union[str, None] = '094211e8220b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_created', 'notifications', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_created', 'notifications', ['user_id', 'created'])
    # ### end Alembic commands ###
