"""added indexing

Revision ID: 99df50eb5f2e
Revises: 7681473497d9
Create Date: 2025-06-29 12:24:09.056036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99df50eb5f2e'
down_revision: Union[str, None] = '7681473497d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_collection_project_id_name', 'collections', ['name', 'project_id'], unique=False)
    op.create_index(op.f('ix_collections_project_id'), 'collections', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collections_project_id'), table_name='collections')
    op.drop_index('idx_collection_project_id_name', table_name='collections')
    # ### end Alembic commands ###
