"""working on cascade

Revision ID: adafa330a0eb
Revises: 92e85869eebd
Create Date: 2025-10-18 11:36:43.980267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adafa330a0eb'
down_revision: Union[str, None] = '92e85869eebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('collections_project_id_fkey', 'collections', type_='foreignkey')
    op.create_foreign_key(None, 'collections', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collections', type_='foreignkey')
    op.create_foreign_key('collections_project_id_fkey', 'collections', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
