"""update to cloud func model

Revision ID: d7af5c645512
Revises: 3d6b5b575219
Create Date: 2025-11-04 17:47:13.518139

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d7af5c645512"
down_revision: Union[str, None] = "3d6b5b575219"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Remove duplicate entries before adding unique constraint
    # Keep the oldest entry for each (project_id, name) pair and delete the rest
    conn = op.get_bind()
    conn.execute(
        sa.text(
            """
        DELETE FROM cloud_functions
        WHERE id NOT IN (
            SELECT MIN(id)
            FROM cloud_functions
            GROUP BY project_id, name
        )
    """
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_project_function_name", "cloud_functions", ["project_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_project_function_name", "cloud_functions", type_="unique")
    # ### end Alembic commands ###
