"""adding api calls tracker

Revision ID: ddfd291e3bfc
Revises: 1e5eff044b79
Create Date: 2025-10-22 11:15:06.285026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddfd291e3bfc'
down_revision: Union[str, None] = '1e5eff044b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_month', 'api_usage_counters', ['project_id', 'month'], unique=True)
    op.create_index(op.f('ix_api_usage_counters_project_id'), 'api_usage_counters', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_usage_counters_project_id'), table_name='api_usage_counters')
    op.drop_index('idx_project_month', table_name='api_usage_counters')
    op.drop_table('api_usage_counters')
    # ### end Alembic commands ###
