"""removed unique from appuser oauth_id field

Revision ID: e45bd15f6624
Revises: 01c2ee94ff5f
Create Date: 2026-01-15 20:12:36.547241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e45bd15f6624'
down_revision: Union[str, None] = '01c2ee94ff5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('app_users_oauth_id_key', 'app_users', type_='unique')


def downgrade() -> None:
    """Downgrade schema."""

    op.create_unique_constraint('app_users_oauth_id_key', 'app_users', ['oauth_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
