"""adding notifications

Revision ID: f3254218ba4f
Revises: a9fd3087a2aa
Create Date: 2025-10-11 16:36:30.297386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3254218ba4f'
down_revision: Union[str, None] = 'a9fd3087a2aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_app_users_client_id'), 'app_users', ['client_id'], unique=False)
    op.create_unique_constraint('uq_client_email', 'app_users', ['client_id', 'email'])
    op.create_unique_constraint(None, 'app_users', ['oauth_id'])
    op.create_foreign_key(None, 'app_users', 'projects', ['client_id'], ['id'])
    op.alter_column('cloud_functions', 'runtime',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'cloud_functions', 'projects', ['project_id'], ['id'])
    op.create_index('idx_collection_project_id_name', 'collections', ['name', 'project_id'], unique=False)
    op.create_index(op.f('ix_collections_project_id'), 'collections', ['project_id'], unique=False)
    op.create_foreign_key(None, 'collections', 'projects', ['project_id'], ['id'])
    op.create_index(op.f('ix_documents_collection_id'), 'documents', ['collection_id'], unique=False)
    op.create_index('ix_documents_data_gin', 'documents', ['data'], unique=False, postgresql_using='gin', postgresql_ops={'data': 'jsonb_ops'})
    op.create_foreign_key(None, 'documents', 'collections', ['collection_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'function_executions', 'cloud_functions', ['function_id'], ['id'])
    op.create_index(op.f('ix_pricing_plans_id'), 'pricing_plans', ['id'], unique=False)
    op.create_unique_constraint(None, 'pricing_plans', ['name'])
    op.create_foreign_key(None, 'project_shares', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'project_shares', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_project_subscriptions_id'), 'project_subscriptions', ['id'], unique=False)
    op.create_foreign_key(None, 'project_subscriptions', 'pricing_plans', ['plan_id'], ['id'])
    op.create_foreign_key(None, 'project_subscriptions', 'projects', ['project_id'], ['id'])
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'projects', ['api_key'])
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'])
    op.create_unique_constraint('uq_route_created', 'route_hits', ['route', 'created'])
    op.create_unique_constraint('uq_user_suggestion', 'suggestion_likes', ['user_id', 'suggestion_id'])
    op.create_foreign_key(None, 'suggestion_likes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'suggestion_likes', 'suggestions', ['suggestion_id'], ['id'])
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_constraint(None, 'suggestion_likes', type_='foreignkey')
    op.drop_constraint(None, 'suggestion_likes', type_='foreignkey')
    op.drop_constraint('uq_user_suggestion', 'suggestion_likes', type_='unique')
    op.drop_constraint('uq_route_created', 'route_hits', type_='unique')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_constraint(None, 'project_subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'project_subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_project_subscriptions_id'), table_name='project_subscriptions')
    op.drop_constraint(None, 'project_shares', type_='foreignkey')
    op.drop_constraint(None, 'project_shares', type_='foreignkey')
    op.drop_constraint(None, 'pricing_plans', type_='unique')
    op.drop_index(op.f('ix_pricing_plans_id'), table_name='pricing_plans')
    op.drop_constraint(None, 'function_executions', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index('ix_documents_data_gin', table_name='documents', postgresql_using='gin', postgresql_ops={'data': 'jsonb_ops'})
    op.drop_index(op.f('ix_documents_collection_id'), table_name='documents')
    op.drop_constraint(None, 'collections', type_='foreignkey')
    op.drop_index(op.f('ix_collections_project_id'), table_name='collections')
    op.drop_index('idx_collection_project_id_name', table_name='collections')
    op.drop_constraint(None, 'cloud_functions', type_='foreignkey')
    op.alter_column('cloud_functions', 'runtime',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'app_users', type_='foreignkey')
    op.drop_constraint(None, 'app_users', type_='unique')
    op.drop_constraint('uq_client_email', 'app_users', type_='unique')
    op.drop_index(op.f('ix_app_users_client_id'), table_name='app_users')
    # ### end Alembic commands ###
