"""settup user model for sqladmin

Revision ID: fbe9db81a870
Revises: 31e44d1d264f
Create Date: 2025-09-17 22:05:28.778567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbe9db81a870'
down_revision: Union[str, None] = '31e44d1d264f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_storage')
    op.drop_table('uploaded_files')
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_staff')
    op.create_table('uploaded_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('public_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('format', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_type', postgresql.ENUM('image', 'video', 'other', name='filetype'), autoincrement=False, nullable=True),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='uploaded_files_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='uploaded_files_pkey')
    )
    op.create_table('user_storage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('used_storage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_storage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_storage_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_storage_pkey'),
    sa.UniqueConstraint('user_id', name='user_storage_user_id_key')
    )
    # ### end Alembic commands ###
