"""removed project limit

Revision ID: fe3410b2dba4
Revises: fbe9db81a870
Create Date: 2025-09-18 09:59:45.513547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe3410b2dba4'
down_revision: Union[str, None] = 'fbe9db81a870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing_plans', 'max_projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_plans', sa.Column('max_projects', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
