# fly.toml app configuration file generated for futurebase on 2025-06-08T15:57:50+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'futurebase'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "60s"
    method = "GET"
    path = "/health/"
    timeout = "5s"
    type = "http"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2